query ShopQuery {
  shop {
    id
    title
    defaultDomain
    contactPhone
    contactEmail
    whatsAppNumber
    whatsAppLink
    facebookLink
    instagramLink
    currencyCode
    about
    shopProductsCategory
    seoDescription
    seoKeywords
    seoTitle
    images{
      siteLogo{
        url
        altText
      }
      favicon{
        url
        altText
      }
      banner{
        url
        altText
      }
      coverImage{
        url
        altText
      }
      siteLogoDark{
        url
        altText
      }
      bannerDark{
        url
        altText
      }
      coverImageDark{
        url
        altText
      }
    }
  }
}
