apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup-secret.yaml
  - scheduled-backup.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: cnpg-backup
      app.kubernetes.io/part-of: naytife-platform
