package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/petrejonn/naytife/internal/db"
	"github.com/petrejonn/naytife/internal/graph/generated"
	"github.com/petrejonn/naytife/internal/graph/model"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, shop model.CreateShopInput) (model.CreateShopPayload, error) {
	fakeAuthSub := "9vgPO5K5ipI424xe84HUrtqQJMWT3e7f@clients"
	owner, err := r.Repository.GetUser(ctx, pgtype.Text{String: fakeAuthSub, Valid: true})
	if err != nil {
		return nil, errors.New("user not found")
	}
	host, ok := ctx.Value("shopHost").(string)
	if !ok {
		return nil, errors.New("host not found")
	}
	param := db.CreateShopParams{
		Title:        shop.Title,
		Domain:       shop.Domain + "." + host,
		OwnerID:      owner.UserID,
		Status:       model.ShopStatusPublished.String(),
		CurrencyCode: "NGN",
	}
	dbShop, err := r.Repository.CreateShop(ctx, param)
	if err != nil {
		return nil, err
	}
	return &model.CreateShopSuccess{Shop: &model.Shop{
		CurrencyCode:  dbShop.CurrencyCode,
		Status:        model.ShopStatus(dbShop.Status),
		Title:         dbShop.Title,
		DefaultDomain: dbShop.Domain,
	}}, nil
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, shop model.UpdateShopInput) (model.UpdateShopPayload, error) {
	shopID := ctx.Value("shop_id").(int64)
	if shop.ContactPhone != nil && !IsValidE164(shop.ContactPhone.E164) {
		return nil, fmt.Errorf("invalid E164 phone number")
	}
	params := db.UpdateShopParams{
		ShopID:         shopID,
		Title:          pgTextFromStringPointer(shop.Title),        // Pass the pointer, no need to dereference here
		CurrencyCode:   pgTextFromStringPointer(shop.CurrencyCode), // Pass the pointer
		About:          pgTextFromStringPointer(shop.About),
		SeoTitle:       pgTextFromStringPointer(shop.SeoTitle),
		SeoDescription: pgTextFromStringPointer(shop.SeoDescription),
		Email:          pgTextFromStringPointer(shop.ContactEmail),
		PhoneNumber:    pgTextFromStringPointer(&shop.ContactPhone.E164),
		Address:        pgTextFromStringPointer(&shop.Address.Address),
	}

	dbShop, err := r.Repository.UpdateShop(ctx, params)

	if err != nil {
		return nil, err
	}
	return &model.UpdateShopSuccess{Shop: &model.Shop{
		CurrencyCode:   dbShop.CurrencyCode,
		Status:         model.ShopStatus(dbShop.Status),
		Title:          dbShop.Title,
		DefaultDomain:  dbShop.Domain,
		About:          &dbShop.About.String,
		SeoTitle:       &dbShop.SeoTitle.String,
		SeoDescription: &dbShop.SeoDescription.String,
		ContactEmail:   &dbShop.Email,
		ContactPhone: &model.PhoneNumber{
			E164: dbShop.PhoneNumber.String,
		},
		Address: &model.ShopAddress{
			Address: dbShop.Address.String,
		},
	}}, nil
}

// CreateWhatsApp is the resolver for the createWhatsApp field.
func (r *mutationResolver) CreateWhatsApp(ctx context.Context, input model.CreateWhatsAppInput) (model.CreateWhatsAppPayload, error) {
	panic(fmt.Errorf("not implemented: CreateWhatsApp - createWhatsApp"))
}

// UpdateWhatsApp is the resolver for the updateWhatsApp field.
func (r *mutationResolver) UpdateWhatsApp(ctx context.Context, input model.UpdateWhatsAppInput) (model.UpdateWhatsAppPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateWhatsApp - updateWhatsApp"))
}

// Shop is the resolver for the shop field.
func (r *queryResolver) Shop(ctx context.Context) (*model.Shop, error) {
	shopID := ctx.Value("shop_id").(int64)
	shop, err := r.Repository.GetShop(ctx, shopID)
	if err != nil {
		return nil, err
	}
	return &model.Shop{
		Title:          shop.Title,
		DefaultDomain:  shop.Domain,
		CurrencyCode:   shop.CurrencyCode,
		Status:         model.ShopStatus(shop.Status),
		About:          &shop.About.String,
		SeoDescription: &shop.SeoDescription.String,
		SeoTitle:       &shop.SeoTitle.String,
		UpdatedAt:      shop.UpdatedAt.Time,
		CreatedAt:      shop.CreatedAt.Time,
		ContactEmail:   &shop.Email,
		ContactPhone: &model.PhoneNumber{
			E164: shop.PhoneNumber.String,
		},
		Address: &model.ShopAddress{
			Address: shop.Address.String,
		},
	}, nil
}

// ID is the resolver for the id field.
func (r *shopResolver) ID(ctx context.Context, obj *model.Shop) (string, error) {
	// Return the base64-encoded ID
	return EncodeRelayID("Category", obj.ID), nil
}

// Products is the resolver for the products field.
func (r *shopResolver) Products(ctx context.Context, obj *model.Shop, first *int, after *string) (*model.ProductConnection, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Categories is the resolver for the categories field.
func (r *shopResolver) Categories(ctx context.Context, obj *model.Shop, first *int, after *string) (*model.CategoryConnection, error) {
	shopID := ctx.Value("shop_id").(int64)
	limit := 20
	if first != nil {
		limit = *first
	}
	afterID := int64(0)
	if after != nil {
		decodedType, id, err := DecodeRelayID(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		if decodedType != "Category" {
			return nil, fmt.Errorf("expected after cursor type 'Category', got '%s'", decodedType)
		}
		if id != nil {
			afterID = *id // The actual ID is retrieved here
		}
	}
	categoriesDB, err := r.Repository.GetCategories(ctx, db.GetCategoriesParams{ShopID: shopID, After: afterID, Limit: int32(limit) + 1})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch categories: %w", err)
	}
	hasNextPage := len(categoriesDB) > limit
	if hasNextPage {
		categoriesDB = categoriesDB[:limit] // Trim the extra item
	}
	edges := make([]model.CategoryEdge, len(categoriesDB))
	for i, cat := range categoriesDB {
		relayID := EncodeRelayID("Category", strconv.FormatInt(cat.CategoryID, 10))
		edges[i] = model.CategoryEdge{Cursor: relayID, Node: &model.Category{
			ID:          relayID,
			Slug:        cat.Slug,
			Title:       cat.Title,
			Description: cat.Description.String,
			CreatedAt:   cat.CreatedAt.Time,
			UpdatedAt:   cat.UpdatedAt.Time,
		}}
	}
	var startCursor, endCursor *string
	if len(categoriesDB) > 0 {
		firstCursor := EncodeRelayID("Category", strconv.FormatInt(categoriesDB[0].CategoryID, 10))
		lastCursor := EncodeRelayID("Category", strconv.FormatInt(categoriesDB[len(categoriesDB)-1].CategoryID, 10))
		startCursor, endCursor = &firstCursor, &lastCursor
	}

	pageInfo := &model.PageInfo{
		HasNextPage: hasNextPage,
		StartCursor: *startCursor,
		EndCursor:   *endCursor,
	}

	// Return the CategoryConnection result
	return &model.CategoryConnection{
		Edges:    edges,
		PageInfo: pageInfo,
	}, nil
}

// Shop returns generated.ShopResolver implementation.
func (r *Resolver) Shop() generated.ShopResolver { return &shopResolver{r} }

type shopResolver struct{ *Resolver }
