query ProductQuery($pid:ID!) {
  product(id: $pid) {
       id
        productId
        slug
        title
        description
        updatedAt
        createdAt
        images{
          url
          altText
        }
        attributes{
          title
          value
        }
        defaultVariant {
          id
          variationId
          price
          attributes{
            title
            value
          }
          availableQuantity
          description
          stockStatus
        }
        variants {
          id
          variationId
          attributes{
            title
            value
          }
          price
          availableQuantity
          description
          stockStatus
        }
  }
}