[build]
# Change directory to backend and build the Go application
commands = [
  "cd backend",
  "go mod tidy",
  "go build -o bin/api"  # Make sure this matches your binary output
]

[run]
# Specify the binary or entrypoint for running the application
command = "./backend/bin/api"
