[[phases.install]]
cmds = ["cd backend", "go mod tidy"]

[[phases.build]]
cmds = ["cd backend", "make build"]

[[phases.start]]
cmd = "cd backend && ./bin/api"  # Use the correct start command for your app
