apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-handler
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: auth-handler
    app.kubernetes.io/part-of: naytife-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-handler
  template:
    metadata:
      labels:
        app: auth-handler
        app.kubernetes.io/name: auth-handler
        app.kubernetes.io/part-of: naytife-platform
    spec:
      containers:
      - name: auth-handler
        image: naytife/auth-handler:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: auth-handler-config
        - secretRef:
            name: auth-handler-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
