apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: auth
      app.kubernetes.io/version: v1.0.0

images:
  - name: naytife/auth-handler
    newTag: latest
