apiVersion: v1
kind: Service
metadata:
  name: auth-handler
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: auth-handler
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: auth-handler
