apiVersion: ENC[AES256_GCM,data:wKQ=,iv:5AB34SxdDG3qkCs0GRMPO9SFi0370pP7HA3GiS+f47w=,tag:fBwj/7R/Ey7ck7cvoLXmiw==,type:str]
kind: ENC[AES256_GCM,data:c6vveidu,iv:2tHNUy9TNTKEALTS2pAWGvRR6/ZUKMmJATMTNhcsAUA=,tag:M1VIb1kXVcMcUSb19XlPbA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ZIsge/hezTb5nDGrPRVgMmI=,iv:SDLyIvp2kSxufGeKQSar/6Jij5jT0j16yS2jVecap7Q=,tag:2pbxi/2h7zTBZJVQJSa4FA==,type:str]
  namespace: ENC[AES256_GCM,data:I8MmvHx6FZbT5DBh,iv:/6aD72TePN1rj4f2TKdROfkB+F/SqE74SQU4UbvIQnQ=,tag:zw+v++tYksKzE8QmscuEbQ==,type:str]
type: ENC[AES256_GCM,data:eDVX3Ms7,iv:aWpF+N2QpEYPYzaHerSXdnWDDWQ9jKBSAY53cswSvNo=,tag:efCfPSp6fz4cLGGKlG54Eg==,type:str]
stringData:
  oauth2-client-id: ENC[AES256_GCM,data:kZkyTqANGjAKcGAABJvcBoaS6xv8xnqpYxJXtRBLRLeFcLUZ,iv:wcI1EXbetCGapT+DZRncedhVAvqoLP5KeKt7S8IVp7I=,tag:9OZWKkMRkev1khSmCl2dgg==,type:str]
  oauth2-client-secret: ENC[AES256_GCM,data:naozEI17YX+H2pLy6yl/uDoYlL3apY4Ce2Q=,iv:9mipiWX8HfZILVui4w+VGQMkdDbSbVp9ACWYrt2Rsx4=,tag:AevPaCCmDCKEFYX7+F48mg==,type:str]
sops:
  age:
    - recipient: age1z2g7cvuq2yus0n4y0aq5t5ww82w06zafrw3ldfka4tzhkl4fafkstj4pk6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3anZOVjdXVWlQK1RXQlor
        Nng2RnpkKzJkTTd1bksraUkzcEhXb3RGQXdjCjhGc1RmYzJYak5YaVg5SEtZRXFL
        QUxWbDBOcSt3cExxc3pOZmVIell2UWsKLS0tIFdmQ0ErZ1BhdjZLL01UQmt6NnR0
        REYyRjJGZCtkeVhGenpXWFpmWTg5akUKXQ4BLQCxWaKJh9K3DAY0srWe6k9OI24n
        reEc9kftO96itybceC/KoMHu7sKSEDZS0E4T57igq5CqB3lGTnQqkA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1fpm9vrkrufeck4gqetarr5dqzn5yp7n9lucyczef7ytl7ppt9qls2vgzrc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbWxNTDJUTFM5Vko0enlC
        NzZDaVNUVGFJNXAwQnZnRVJ1dkNDTzBoR2dBClRjWklVYXF6Q096U1RWTEwzcXpV
        eFI1OXBmdmtHUWE3VFVpMmYzM05aem8KLS0tIGlzNUJqZkZEd1NRUys5eEF3SGpZ
        bWl2T01yWDNlcWU5bW9kMStqbEF0R3cKGTAdrKQnLURmPjSsv4/0n9KJGKp8qK9r
        6d0O9VhInBlWKkDODgFrmFQOKKAHqTTRwFObWJq88oINFdHCMU0Dkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-13T20:53:30Z"
  mac: ENC[AES256_GCM,data:rVKzNP4ZSHJarhVOZC51QTVYH5cgfdDbNBrgpGvWP8S7ZQuxBqv8dujTcrnbiStyV4YFjLAhCmLvKTY3bFXHq5W+ytVxqNiM8WNk21KZ8L/OZRUq8zjz8C9T7uvFuZeGNzDhaXfZN4GAAXNThBewCmikmNHcl8PqcIQxLMMEqYg=,iv:1cBShuRvvqu0a+AxXrZOyU+kJPsft8w6IwXssHZVdzU=,tag:CwyhoI3memhXCFd7Z62uSQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
