apiVersion: ENC[AES256_GCM,data:Q04=,iv:FN0WNA3p6bSJ0+P9j4nfaVekFHWudzIB8xprw4U/Ls4=,tag:xBdyZriUMuElfS9RstW1+w==,type:str]
kind: ENC[AES256_GCM,data:WGOfcelN,iv:iorw/MRibbhqQK0RKxtuRBzTuYFqkVSDEHHe6ZEOA8k=,tag:cXZ6RH1AiBsnPZIm7ls13w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/fDVsRb6+319vijG,iv:teA8KPq2/21G4+7rHBKykBxLNlSWjsjC0kg+GZE7vX0=,tag:zndz16n3efraeraHWEi+qg==,type:str]
    namespace: ENC[AES256_GCM,data:FJlxZbiJ7g==,iv:fEUqUYwxq9uD8AU0/g4C2H+XLmRlLO8qFvFmXgYnHI4=,tag:3KSzDsvMQNDTvQs1STOewg==,type:str]
type: ENC[AES256_GCM,data:8H6GGL9G,iv:maGspkYsUf9l5nLQmxpaVTXOVvpKlog0TDZ7OSoafBw=,tag:W1RHDmHGD/RMkTh/0JuqGg==,type:str]
stringData:
    redis-password: ENC[AES256_GCM,data:I3scfc0uEs7F83oe/nOUVKgx,iv:Xzl8h+xifC2mMQbJ00I+snd/bHVQFPv7P2ItZQ5rspE=,tag:2/9bEEKfe8TnlfsxaCZ17w==,type:str]
sops:
    age:
        - recipient: age1z2g7cvuq2yus0n4y0aq5t5ww82w06zafrw3ldfka4tzhkl4fafkstj4pk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blpBTDVkM2NZZ1JWS2Ur
            NWd6cE1qemJmM28xOEwvWGptRXlGVmpJNWs0CnBzNGlxazZPc2Z6L3J2NjlzeHQ4
            TkZLOGwxM0hremlhU3RQUy9zeExod3cKLS0tIDZBR01qR2kwOGpGUDFhWGRRd2pa
            WG14dk5FaWtzWkVJOWdtUlFYREY3MVEKza7z2GJWwVz5mXKELvGQm/TVfTWpROQw
            r8ciKx+U6GJ91rAeCipB/iHOCpbTCEXMZV4BJqyPJEGDuG5X3MSyRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T11:55:51Z"
    mac: ENC[AES256_GCM,data:qohZqROCsHObwNFqoAou+7RUNG1/n+Kg4ik8n/UaVEB74PFdnEq0NSeHq9S7pv0jWDsvBzxP7Ut+p+jErP3QSaOVFX2M3nzW1XdhYvBKJCbRo6I2RjGTEAe04d6wGq/5FuLf2/1Qo0FutvYDezWbI615hOzbxF+zmonzBUSkem4=,iv:mnph4dZbSzXm2M8ObSk0EPZmR9/QXF1zvaglIKjBhxg=,tag:5spqOiPGMkI3yomlFJpeKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
