apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: naytife
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
