apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: naytife
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: naytife-platform
data:
  PORT: "8000"
  API_URL: "http://127.0.0.1:8080"
  REDIS_ADDR: "redis.naytife.svc.cluster.local:6379"
  REDIS_URL: "redis://:naytife-redis-2024@redis.naytife.svc.cluster.local:6379"
  HYDRA_ADMIN_URL: "http://hydra-admin.naytife-auth.svc.cluster.local:4445"
  HYDRA_PUBLIC_URL: "http://hydra-public.naytife-auth.svc.cluster.local:4444"
  AUTH_HANDLER_URL: "http://auth-handler.naytife-auth.svc.cluster.local:3000"
  # Microservice URLs for Backend for Frontend pattern
  TEMPLATE_REGISTRY_URL: "http://template-registry.naytife.svc.cluster.local:9001"
  STORE_DEPLOYER_URL: "http://store-deployer.naytife.svc.cluster.local:9003"
  CORS_ALLOWED_ORIGINS: "*"
  LOG_LEVEL: "info"
  APP_ENV: "development"
