apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: naytife
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: naytife-platform
data:
  PORT: "8000"
  # Environment-specific URLs are set in overlay patches
  # API_URL, REDIS_ADDR, REDIS_URL, HYDRA_ADMIN_URL, HYDRA_PUBLIC_URL, 
  # AUTH_HANDLER_URL, TEMPLATE_REGISTRY_URL, STORE_DEPLOYER_URL
  # are configured per environment in overlays
  CORS_ALLOWED_ORIGINS: "*"
  LOG_LEVEL: "info"
  APP_ENV: "development"
