apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: naytife
  labels:
    app.kubernetes.io/name: backend-migrate
    app.kubernetes.io/part-of: naytife-platform
    app.kubernetes.io/component: migration
    app.kubernetes.io/version: "v1.1"
spec:
  # Allow up to 3 retries if migration fails
  backoffLimit: 3
  # Remove completed jobs after 24 hours
  ttlSecondsAfterFinished: 86400
  # Active deadline for the job (10 minutes max)
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: backend-migrate
        app.kubernetes.io/name: backend-migrate
        app.kubernetes.io/part-of: naytife-platform
      annotations:
        kubectl.kubernetes.io/default-container: atlas-migrate
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h naytife-postgres-pooler.naytife.svc.cluster.local -p 5432 -U naytife; do
            echo "PostgreSQL not ready, waiting 2 seconds..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready!"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      
      - name: migration-pre-check
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          echo "🔍 Running pre-migration checks..."
          
          # Check if database exists and is accessible
          PGPASSWORD=$POSTGRES_PASSWORD psql -h naytife-postgres-pooler.naytife.svc.cluster.local -U naytife -d naytifedb -c "SELECT version();" || exit 1
          
          # Check if schema exists
          PGPASSWORD=$POSTGRES_PASSWORD psql -h naytife-postgres-pooler.naytife.svc.cluster.local -U naytife -d naytifedb -c "CREATE SCHEMA IF NOT EXISTS naytife_schema;" || exit 1
          
          echo "✅ Pre-migration checks passed"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-secret
              key: password
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      
      containers:
      - name: atlas-migrate
        image: naytife/backend-migrations:latest
        imagePullPolicy: Never
        command:
        - sh
        - -c
        - |
          # Build a clean PostgreSQL URL using direct connection (not pooler)
          export DB_URL="postgresql://naytife:$POSTGRES_PASSWORD@naytife-postgres-rw.naytife.svc.cluster.local:5432/naytifedb?sslmode=require"
          
          echo "🔍 Checking current migration status..."
          atlas migrate status \
            --dir file:///migrations \
            --url "$DB_URL" \
            --revisions-schema atlas_schema_revisions
          
          echo "⚡ Applying migrations..."
          atlas migrate apply \
            --dir file:///migrations \
            --url "$DB_URL" \
            --revisions-schema atlas_schema_revisions \
            --tx-mode none \
            --allow-dirty
          
          echo "✅ Migration completed successfully!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-secret
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
 