apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: naytife
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: backend
