apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployer
  namespace: naytife
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-deployer
  template:
    metadata:
      labels:
        app: store-deployer
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
      - name: store-deployer
        image: docker.io/library/store-deployer:latest
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 9003
        env:
        - name: CLOUDFLARE_R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: access-key-id
        - name: CLOUDFLARE_R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: secret-access-key
        - name: CLOUDFLARE_R2_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: endpoint
        - name: CLOUDFLARE_R2_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: stores-bucket-name
        - name: CLOUDFLARE_R2_TEMPLATES_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: templates-bucket-name
        - name: CLOUDFLARE_R2_IMAGES_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: cloudflare-secrets
              key: images-bucket-name
        - name: BACKEND_URL
          value: "http://backend:8002"
        - name: TEMPLATE_REGISTRY_URL
          value: "http://template-registry:9001"
        - name: PORT
          value: "9003"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: store-deployer
  namespace: naytife
spec:
  selector:
    app: store-deployer
  ports:
  - name: http
    port: 9003
    targetPort: 9003
  type: ClusterIP
