-- Create enum type "product_status"
CREATE TYPE "product_status" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');
-- Create enum type "attribute_data_type"
CREATE TYPE "attribute_data_type" AS ENUM ('Text', 'Number', 'Date', 'Option');
-- Create enum type "attribute_unit"
CREATE TYPE "attribute_unit" AS ENUM ('KG', 'GB', 'INCH');
-- Create enum type "attribute_applies_to"
CREATE TYPE "attribute_applies_to" AS ENUM ('Product', 'ProductVariation');
-- Create "users" table
CREATE TABLE "users" ("user_id" uuid NOT NULL DEFAULT gen_random_uuid(), "sub" character varying(255) NULL, "email" character varying(255) NULL, "provider" character varying(255) NULL, "provider_id" character varying(255) NULL, "name" character varying(255) NULL, "locale" character varying(255) NULL, "profile_picture" text NULL, "created_at" timestamp NULL DEFAULT now(), "last_login" timestamp NULL, PRIMARY KEY ("user_id"), CONSTRAINT "users_email_key" UNIQUE ("email"), CONSTRAINT "users_sub_key" UNIQUE ("sub"));
-- Create "shops" table
CREATE TABLE "shops" ("shop_id" bigserial NOT NULL, "owner_id" uuid NOT NULL, "title" character varying(50) NOT NULL, "domain" character varying(50) NOT NULL, "email" character varying(50) NOT NULL, "currency_code" character varying(3) NOT NULL, "status" character varying(10) NOT NULL, "about" text NULL, "address" text NULL, "phone_number" character varying(16) NULL, "whatsapp_phone_number" character varying(16) NULL, "whatsapp_link" text NULL, "facebook_link" text NULL, "instagram_link" text NULL, "seo_description" text NULL, "seo_keywords" text[] NULL, "seo_title" character varying(255) NULL, "updated_at" timestamptz NOT NULL DEFAULT now(), "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("shop_id"), CONSTRAINT "shops_domain_key" UNIQUE ("domain"), CONSTRAINT "fk_owner" FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "attributes" table
CREATE TABLE "attributes" ("attribute_id" bigserial NOT NULL, "title" character varying(50) NOT NULL, "data_type" "attribute_data_type" NOT NULL DEFAULT 'Text', "unit" "attribute_unit" NULL, "required" boolean NOT NULL DEFAULT false, "applies_to" "attribute_applies_to" NOT NULL DEFAULT 'Product', "shop_id" bigint NOT NULL, PRIMARY KEY ("attribute_id"), CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "attribute_options" table
CREATE TABLE "attribute_options" ("attribute_option_id" bigserial NOT NULL, "value" character varying(50) NOT NULL, "shop_id" bigint NOT NULL, "attribute_id" bigint NOT NULL, PRIMARY KEY ("attribute_option_id"), CONSTRAINT "fk_attribute" FOREIGN KEY ("attribute_id") REFERENCES "attributes" ("attribute_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "categories" table
CREATE TABLE "categories" ("category_id" bigserial NOT NULL, "slug" character varying(50) NOT NULL, "title" character varying(50) NOT NULL, "description" character varying(255) NULL, "parent_id" bigint NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("category_id"), CONSTRAINT "categories_slug_shop_id_key" UNIQUE ("slug", "shop_id"), CONSTRAINT "categories_title_shop_id_key" UNIQUE ("title", "shop_id"), CONSTRAINT "fk_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("category_id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "orders" table
CREATE TABLE "orders" ("order_id" bigserial NOT NULL, "status" character varying(10) NOT NULL, "total_price" numeric(10,2) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, PRIMARY KEY ("order_id"), CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_types" table
CREATE TABLE "product_types" ("product_type_id" bigserial NOT NULL, "title" character varying(50) NOT NULL, "shippable" boolean NOT NULL DEFAULT true, "digital" boolean NOT NULL DEFAULT false, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_type_id"), CONSTRAINT "product_types_title_shop_id_key" UNIQUE ("title", "shop_id"), CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "products" table
CREATE TABLE "products" ("product_id" bigserial NOT NULL, "title" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "product_type_id" bigint NOT NULL, "category_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_id"), CONSTRAINT "products_title_shop_id_key" UNIQUE ("title", "shop_id"), CONSTRAINT "fk_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_product_type" FOREIGN KEY ("product_type_id") REFERENCES "product_types" ("product_type_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_variations" table
CREATE TABLE "product_variations" ("product_variation_id" bigserial NOT NULL, "sku" character varying(50) NOT NULL, "slug" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, "price" numeric(10,2) NOT NULL, "available_quantity" bigint NOT NULL, "status" "product_status" NOT NULL DEFAULT 'DRAFT', "seo_description" text NULL, "seo_keywords" text[] NULL, "seo_title" character varying(255) NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "product_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_variation_id"), CONSTRAINT "product_variations_slug_shop_id_key" UNIQUE ("slug", "shop_id"), CONSTRAINT "fk_product" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "order_items" table
CREATE TABLE "order_items" ("order_item_id" bigserial NOT NULL, "quantity" bigint NOT NULL, "price" numeric(10,2) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "product_variation_id" bigint NOT NULL, "order_id" bigint NOT NULL, PRIMARY KEY ("order_item_id"), CONSTRAINT "fk_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_product_variation" FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("product_variation_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_attribute_values" table
CREATE TABLE "product_attribute_values" ("product_attribute_value_id" bigserial NOT NULL, "value" character varying(50) NULL, "attribute_option_id" bigint NULL, "product_id" bigint NOT NULL, "attribute_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_attribute_value_id"), CONSTRAINT "fk_attribute" FOREIGN KEY ("attribute_id") REFERENCES "attributes" ("attribute_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_attribute_option" FOREIGN KEY ("attribute_option_id") REFERENCES "attribute_options" ("attribute_option_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_product" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_images" table
CREATE TABLE "product_images" ("product_image_id" bigserial NOT NULL, "url" text NOT NULL, "alt" character varying(255) NOT NULL, "product_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_image_id"), CONSTRAINT "fk_product" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_variation_attribute_values" table
CREATE TABLE "product_variation_attribute_values" ("product_variation_attribute_value_id" bigserial NOT NULL, "value" character varying(50) NULL, "attribute_option_id" bigint NULL, "product_variation_id" bigint NOT NULL, "attribute_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("product_variation_attribute_value_id"), CONSTRAINT "fk_attribute" FOREIGN KEY ("attribute_id") REFERENCES "attributes" ("attribute_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_attribute_option" FOREIGN KEY ("attribute_option_id") REFERENCES "attribute_options" ("attribute_option_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_product_variation" FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("product_variation_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "shop_images" table
CREATE TABLE "shop_images" ("shop_image_id" bigserial NOT NULL, "favicon_url" text NULL, "logo_url" text NULL, "banner_url" text NULL, "cover_image_url" text NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("shop_image_id"), CONSTRAINT "shop_images_shop_id_key" UNIQUE ("shop_id"), CONSTRAINT "fk_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("shop_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "shopping_cart" table
CREATE TABLE "shopping_cart" ("shopping_cart_id" bigserial NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("shopping_cart_id"), CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "shopping_cart_items" table
CREATE TABLE "shopping_cart_items" ("shopping_cart_item_id" bigserial NOT NULL, "quantity" bigint NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "product_variation_id" bigint NOT NULL, "shopping_cart_id" bigint NOT NULL, PRIMARY KEY ("shopping_cart_item_id"), CONSTRAINT "fk_product_variation" FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("product_variation_id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_shopping_cart" FOREIGN KEY ("shopping_cart_id") REFERENCES "shopping_cart" ("shopping_cart_id") ON UPDATE NO ACTION ON DELETE CASCADE);
