apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-handler
  namespace: naytife-auth
spec:
  template:
    spec:
      containers:
      - name: auth-handler
        env:
        - name: APP_ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
