apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-config
  namespace: naytife-auth
data:
  config.yaml: |
    log:
      level: info
      format: json
      leak_sensitive_values: false
    
    serve:
      proxy:
        port: 8080
        host: 0.0.0.0
        cors:
          enabled: true
          allowed_origins:
            - "https://dashboard-staging.naytife.com"
            - "https://*.naytife.com"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - "*"
      api:
        port: 4456
        host: 0.0.0.0
    
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json
    
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: false
        redirect:
          enabled: true
          config:
            to: https://auth-staging.naytife.com/auth/login
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      - text/html
    
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      
      noop:
        enabled: true
      
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin.naytife-auth.svc.cluster.local:4445/admin/oauth2/introspect
          scope_strategy: exact
          trusted_issuers:
            - https://api-staging.naytife.com/
          pre_authorization:
            enabled: true
            client_id: ${OAUTH2_CLIENT_ID}
            client_secret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - introspect
            token_url: http://hydra-public.naytife-auth.svc.cluster.local:4444/oauth2/token
          token_from:
            header: Authorization
          retry:
            max_delay: 300ms
            give_up_after: 2s
          cache:
            enabled: true
            ttl: 60s
      
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://hydra-public.naytife-auth.svc.cluster.local:4444/.well-known/jwks.json
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - https://api-staging.naytife.com/
    
    authorizers:
      allow:
        enabled: true
      
      deny:
        enabled: true
    
    mutators:
      noop:
        enabled: true
      
      header:
        enabled: true
        config:
          headers:
            X-User-Id: "{{ print .Subject }}"
            X-User-Email: "{{ print .Extra.email }}"
            X-User-Name: "{{ print .Extra.name }}"
