version: v0.13.0

dsn: postgres://naytife:naytifekey@postgres.default.svc.cluster.local:5432/naytifedb?sslmode=disable

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/
    
secrets:
  cookie:
    - 4159f931cce7cc16d5c17814d76686d960d6ee40675faca165067eb1faa9bd4fa9beb9e1a2a689b2003355ae5746a283bf591f34dbc0e4d8f4a0685e754455b3
  cipher:
    - Vf2nS{+jwj"{U:BHLZ4V/Mz.As)]uKQ'

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 24
    memory: 128MB
    iterations: 5
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/identity/identity.schema.json
courier:
  smtp:
    connection_uri: smtps://kratos:kratos@mail-smtp:1025/?skip_ssl_verify=true&legacy_ssl=true
selfservice:
  default_browser_return_url: http://127.0.0.1:4455/welcome
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: auth.naytife.com
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    webauthn:
      enabled: true
      config:
        rp:
          id: naytife.com
          origin: http://auth.naytife.com
          display_name: auth.naytife.com

  # automigration:
  #   enabled: true
  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      required_aal: highest_available
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      after:
        default_browser_return_url: http://127.0.0.1:4455/welcome

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
log:
  level: debug
  format: text
  leak_sensitive_values: true
    