image:
  repository: oryd/oathkeeper
  tag: v0.40.7
oathkeeper:
  config:
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json

    errors:
      fallback:
        - json

      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: http://example-idp.local/login # Hydra's login page
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      - text/html

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest

      noop:
        enabled: true

      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin.naytife-ory.svc.cluster.local:4445/oauth2/introspect
          scope_strategy: exact
          required_scope:
            - hydra.openid
            - offline
          trusted_issuers:
            - http://public.hydra.local
          pre_authorization:
            enabled: true
            client_id: 50d1bd9a-a480-491a-b4a3-05307c4aeb43
            client_secret: B7tjVNKXD40xv2NRtRcE7m.Noh
            scope:
              - introspect
            token_url: http://hydra-public.naytife-ory.svc.cluster.local:4444/oauth2/token
          token_from:
            header: Authorization
          retry:
            max_delay: 300ms
            give_up_after: 2s
          cache:
            enabled: true
            ttl: 60s
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://public.hydra.local/.well-known/jwks.json # This URL exposes Hydra's keys for verifying JWTs
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - http://public.hydra.local

    authorizers:
      allow:
        enabled: true
      keto_engine_acp_ory:
        enabled: false
        config:
          base_url: http://keto:4466/engines/acp/ory/exact

    mutators:
      noop:
        enabled: true
