oathkeeper:
  config:
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json 

    errors:
      fallback:
        - json

      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: http://127.0.0.1:3000/login  # Hydra's login page
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      - text/html

    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest

      noop:
        enabled: true

      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra:4445/oauth2/introspect
          scope_strategy: exact
          required_scope:  # You can use this to enforce broad scope checks, but Keto may handle finer-grained access control
            - hydra.openid
            - offline
          trusted_issuers:
            - http://127.0.0.1:4444
          pre_authorization:
            enabled: true
            client_id: your-hydra-client-id
            client_secret: your-hydra-client-secret
            scope:
              - introspect
            token_url: http://hydra:4444/oauth2/token
          token_from:
            header: Authorization 
          retry:
            max_delay: 300ms
            give_up_after: 2s
          cache:
            enabled: true
            ttl: 60s
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://127.0.0.1:4444/.well-known/jwks.json  # This URL exposes Hydra's keys for verifying JWTs
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - http://127.0.0.1:4444

    authorizers:
      allow:
        enabled: true
      keto_engine_acp_ory:
        enabled: false
        config:
          base_url: http://keto:4466/engines/acp/ory/exact

    mutators:
      noop:
        enabled: true