image:
  repository: oryd/oathkeeper
  tag: v0.40.7

oathkeeper:
  config:
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json
    errors:
      handlers:
        json:
          config:
            verbose: true
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      noop:
        enabled: true
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin.auth.svc.cluster.local:4445/oauth2/introspect
          token_from:
            header: Authorization
          token_url: http://hydra-public.auth.svc.cluster.local:4444/oauth2/token
          pre_authorization:
            scope: [introspect]
          required_scope: [hydra.openid, offline]
          trusted_issuers: [https://naytife.com]
          cache:
            enabled: true
            ttl: 60s
      oauth2_client_credentials:
        enabled: true
        config:
          token_url: http://hydra-public.auth:4444/oauth2/token
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://hydra-public.auth:4444/.well-known/jwks.json
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - http://hydra-public.auth:4444
    authorizers:
      allow:
        enabled: true
      keto_engine_acp_ory:
        enabled: true
        config:
          base_url: http://keto-read.auth.svccluster.local:4466
          required_action: "my:action:$1"
          required_resource: "my:resource:$2:foo:$1"
          subject: "{{ .Extra.email }}"
          flavor: exact
    mutators:
      noop:
        enabled: true
      header:
        enabled: true
        config:
          headers:
            X-User-Id: '{{ print .Subject }}'
            X-User-Email: '{{ print .Extra.email }}'