apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
spec:
  template:
    spec:
      containers:
      - name: hydra
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        env:
        - name: DSN
          value: "postgres://naytife:naytife_password_change_in_production@postgres.naytife-oke-free.svc.cluster.local:5432/naytife?sslmode=disable"
      # Ensure pods run on ARM nodes
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
