apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: naytife-oke-free

resources:
  - ../../base
  - ingress-oke.yaml
  - storage-class.yaml
  - namespace.yaml

patches:
  - path: backend-oke-patch.yaml
  - path: auth-handler-oke-patch.yaml
  - path: postgres-oke-patch.yaml
  - path: redis-oke-patch.yaml
  - path: hydra-oke-patch.yaml
  - path: oathkeeper-oke-patch.yaml

images:
  # OCIR registry with ARM64 tags for OKE Always Free
  - name: naytife/backend
    newName: us-ashburn-1.ocir.io/id7dwifk4b9j/naytife/backend
    newTag: arm64-latest
  - name: naytife/auth-handler
    newName: us-ashburn-1.ocir.io/id7dwifk4b9j/naytife/auth-handler
    newTag: arm64-latest
  - name: template-registry
    newName: <region>.ocir.io/<tenancy>/naytife/template-registry
    newTag: arm64-latest
  - name: docker.io/library/store-deployer
    newName: <region>.ocir.io/<tenancy>/naytife/store-deployer
    newTag: arm64-latest

replicas:
  # Optimize for ARM resources - start with single replicas
  - name: backend
    count: 1
  - name: auth-handler
    count: 1
  - name: template-registry
    count: 1
  - name: store-deployer
    count: 1

labels:
  - pairs:
      environment: oke-free
      cloud-provider: oci
      architecture: arm64
    includeSelectors: true
    includeTemplates: true

namespace: naytife-oke-free
