apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-access-rules
  namespace: naytife-auth
data:
  access-rules.json: |
    [
      {
        "id":"api:rest-api-docs",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "https://api.naytife.com/v1/docs",
          "methods": ["GET"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"}, 
        "mutators": [{"handler": "noop"}]
      },
      {
        "id":"api:rest-api-docs-all",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "https://api.naytife.com/v1/docs/<**>",
          "methods": ["GET"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"}, 
        "mutators": [{"handler": "noop"}]
      },
      {
        "id": "api:user-register",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "https://api.naytife.com/v1/auth/register",
          "methods": ["POST"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"},
        "mutators": [{"handler": "noop"}]
      },
      {
        "id": "api:user-login",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "https://api.naytife.com/v1/auth/login",
          "methods": ["POST"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"},
        "mutators": [{"handler": "noop"}]
      },
      {
        "id": "oauth:auth-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "https://api.naytife.com/oauth2/auth",
          "methods": ["GET"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"},
        "mutators": [{"handler": "noop"}]
      },
      {
        "id": "oauth:login-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "https://api.naytife.com/login",
          "methods": ["GET", "POST"]
        },
        "authenticators": [{"handler": "anonymous"}],
        "authorizer": {"handler": "allow"},
        "mutators": [{"handler": "noop"}]
      }
    ]
