apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-registry
  namespace: naytife
spec:
  template:
    spec:
      containers:
      - name: template-registry
        env:
        - name: APP_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "warn"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
