apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - job.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: oauth
      app.kubernetes.io/version: v1.0.0

images:
  - name: oryd/hydra
    newTag: v2.2.0
