apiVersion: v1
kind: Service
metadata:
  name: hydra-public
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/component: public
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 4444
    targetPort: 4444
    name: public
  selector:
    app: hydra
---
apiVersion: v1
kind: Service
metadata:
  name: hydra-admin
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 4445
    targetPort: 4445
    name: admin
  selector:
    app: hydra
