package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"

	"github.com/petrejonn/naytife/internal/db"
	"github.com/petrejonn/naytife/internal/gql/public/generated"
	"github.com/petrejonn/naytife/internal/gql/public/model"
)

// ID is the resolver for the id field.
func (r *productResolver) ID(ctx context.Context, obj *model.Product) (string, error) {
	return encodeRelayID("Product", obj.ID), nil
}

// DefaultVariant is the resolver for the defaultVariant field.
func (r *productResolver) DefaultVariant(ctx context.Context, obj *model.Product) (*model.ProductVariant, error) {
	panic(fmt.Errorf("not implemented: DefaultVariant - defaultVariant"))
}

// Images is the resolver for the images field.
func (r *productResolver) Images(ctx context.Context, obj *model.Product) ([]model.Image, error) {
	panic(fmt.Errorf("not implemented: Images - images"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, first *int, after *string) (*model.ProductConnection, error) {
	shopID := ctx.Value("shop_id").(int64)
	limit := 20
	if first != nil {
		limit = *first
	}
	afterID := int64(0)
	if after != nil {
		decodedType, id, err := decodeRelayID(*after)
		if err != nil {
			return nil, fmt.Errorf("invalid after cursor: %w", err)
		}
		if decodedType != "Product" {
			return nil, fmt.Errorf("expected after cursor type 'Product', got '%s'", decodedType)
		}
		if id != nil {
			afterID = *id
		}
	}
	objsDB, err := r.Repository.GetProducts(ctx, db.GetProductsParams{ShopID: shopID, After: afterID, Limit: int32(limit) + 1})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch products: %w", err)
	}
	hasNextPage := len(objsDB) > limit
	if hasNextPage {
		objsDB = objsDB[:limit]
	}
	edges := make([]model.ProductEdge, len(objsDB))
	for i, prod := range objsDB {
		relayID := encodeRelayID("Product", strconv.FormatInt(prod.ProductID, 10))
		var attributes []model.ProductAttribute
		var variants []model.ProductVariant

		if err := json.Unmarshal(prod.Attributes, &attributes); err != nil {
			return nil, fmt.Errorf("failed to unmarshal attributes: %w", err)
		}

		if err := json.Unmarshal(prod.Variants, &variants); err != nil {
			return nil, fmt.Errorf("failed to unmarshal variants: %w", err)
		}
		edges[i] = model.ProductEdge{Cursor: relayID, Node: &model.Product{
			ID:          strconv.FormatInt(prod.ProductID, 10),
			Title:       prod.Title,
			Description: prod.Description,
			CreatedAt:   prod.CreatedAt.Time,
			UpdatedAt:   prod.UpdatedAt.Time,
			Attributes:  attributes,
			Variants:    variants,
		}}
	}
	var startCursor, endCursor *string
	if len(objsDB) > 0 {
		firstCursor := encodeRelayID("Product", strconv.FormatInt(objsDB[0].ProductID, 10))
		lastCursor := encodeRelayID("Product", strconv.FormatInt(objsDB[len(objsDB)-1].ProductID, 10))
		startCursor, endCursor = &firstCursor, &lastCursor
	}

	pageInfo := &model.PageInfo{
		HasNextPage: hasNextPage,
		StartCursor: safeStringDereference(startCursor),
		EndCursor:   safeStringDereference(endCursor),
	}

	return &model.ProductConnection{
		Edges:      edges,
		PageInfo:   pageInfo,
		TotalCount: len(objsDB),
	}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	shopID := ctx.Value("shop_id").(int64)
	_, objID, err := decodeRelayID(id)
	if err != nil {
		return nil, errors.New("invalid projec ID")
	}
	objDB, err := r.Repository.GetProduct(ctx, db.GetProductParams{ShopID: shopID, ProductID: *objID})
	if err != nil {
		return nil, errors.New("could not find object")
	}
	var attributes []model.ProductAttribute
	var variants []model.ProductVariant

	if err := json.Unmarshal(objDB.Attributes, &attributes); err != nil {
		return nil, fmt.Errorf("failed to unmarshal attributes: %w", err)
	}

	if err := json.Unmarshal(objDB.Variants, &variants); err != nil {
		return nil, fmt.Errorf("failed to unmarshal variants: %w", err)
	}
	return &model.Product{
		ID:          strconv.FormatInt(objDB.ProductID, 10),
		Title:       objDB.Title,
		Description: objDB.Description,
		CreatedAt:   objDB.CreatedAt.Time,
		UpdatedAt:   objDB.UpdatedAt.Time,
		Attributes:  attributes,
		Variants:    variants,
	}, nil
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
