apiVersion: v1
kind: ConfigMap
metadata:
  name: store-deployer-config
  namespace: naytife
  labels:
    app.kubernetes.io/name: store-deployer
    app.kubernetes.io/part-of: naytife-platform
data:
  PORT: "9003"
