apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-config
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/part-of: naytife-platform
data:
  config.yaml: |
    log:
      level: info
      format: json
      leak_sensitive_values: true
    
    serve:
      proxy:
        port: 8080
        host: 0.0.0.0
        cors:
          enabled: true
          allowed_origins:
            - "*"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - "*"
      api:
        port: 4456
        host: 0.0.0.0
    
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json
    
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: http://127.0.0.1:3000/auth/login
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      - text/html
    
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      
      noop:
        enabled: true
      
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: http://hydra-admin.naytife-auth.svc.cluster.local:4445/admin/oauth2/introspect
          scope_strategy: exact
          trusted_issuers:
            - http://127.0.0.1:8080/
          pre_authorization:
            enabled: true
            client_id: 761506cc-511f-411c-bf31-752efd8063b3
            client_secret: z.WE65SP5o0oXDYJwLdyoqYUuN
            scope:
              - introspect
            token_url: http://hydra-public.naytife-auth.svc.cluster.local:4444/oauth2/token
          token_from:
            header: Authorization
          retry:
            max_delay: 300ms
            give_up_after: 2s
          cache:
            enabled: true
            ttl: 60s
      
      jwt:
        enabled: true
        config:
          jwks_urls:
            - http://hydra-public.naytife-auth.svc.cluster.local:4444/.well-known/jwks.json
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - http://127.0.0.1:8080/
    
    authorizers:
      allow:
        enabled: true
      
      deny:
        enabled: true
    
    mutators:
      noop:
        enabled: true
      
      header:
        enabled: true
        config:
          headers:
            X-User-Id: "{{ print .Subject }}"
            X-User-Email: "{{ print .Extra.email }}"
            X-User-Name: "{{ print .Extra.name }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-rules
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/part-of: naytife-platform
data:
  access-rules.json: |
    [
      {
        "id":"api:rest-api-docs",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/v1/docs",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        }, 
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id":"api:rest-api-docs-all",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/v1/docs/<**>",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        }, 
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "api:user-register",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/v1/auth/<{register}>",
          "methods": [
            "POST"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "api:cors",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/<**>",
          "methods": [
            "OPTIONS"
          ]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
                "Access-Control-Allow-Headers": "Authorization, Content-Type"
              }
            }
          }
        ]
      },
      {
        "id": "api:admin-api",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/v1/<{shops,predefined-product-types}><**>",
          "methods": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "PATCH"
          ]
        },
        "authenticators": [
          {
            "handler": "oauth2_introspection"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "header",
            "config": {
              "headers": {
                "X-User-Id": "{{ print .Subject }}",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
                "Access-Control-Allow-Headers": "Authorization, Content-Type"
              }
            }
          }
        ]
      },
      {
        "id": "api:public-graph-playground",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://<*>.localhost:8080/graph",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "api:public-graph-query",
        "upstream": {
          "preserve_host": true,
          "url": "http://backend.naytife:8000"
        },
        "match": {
          "url": "http://<*>.localhost:8080/query",
          "methods": [
            "GET",
            "POST",
            "OPTIONS"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          },
          {
            "handler": "jwt",
            "config": {
              "scope": [
                "shop_customer",
                "offline"
              ]
            }
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:auth-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/oauth2/auth",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:fallbacks-error-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/oauth2/fallbacks/error",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:token-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/oauth2/token",
          "methods": [
            "POST",
            "OPTIONS"
          ]
        },
        "authenticators": [
          {
            "handler": "noop"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:userinfo-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/userinfo",
          "methods": [
            "GET",
            "POST"
          ]
        },
        "authenticators": [
          {
            "handler": "oauth2_introspection"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:logout-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/oauth2/sessions/logout",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "oauth2_introspection"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oidc:well-known",
        "upstream": {
          "preserve_host": true,
          "url": "http://hydra-public.naytife-auth:4444"
        },
        "match": {
          "url": "http://127.0.0.1:8080/.well-known/openid-configuration",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:login-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/login",
          "methods": [
            "GET",
            "POST"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:consent-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/consent",
          "methods": [
            "GET",
            "POST"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:callback-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/callback",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:logout-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/logout",
          "methods": [
            "GET",
            "POST"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "oauth:error-endpoint",
        "upstream": {
          "preserve_host": true,
          "url": "http://auth-handler.naytife-auth:3000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/error",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous"
          }
        ],
        "authorizer": {
          "handler": "allow"
        },
        "mutators": [
          {
            "handler": "noop"
          }
        ]
      },
      {
        "id": "build:service",
        "upstream": {
          "preserve_host": true,
          "url": "http://cloud-build.naytife-build:9000"
        },
        "match": {
          "url": "http://127.0.0.1:8080/build<**>",
          "methods": ["GET", "POST"]
        },
        "authenticators": [{"handler": "oauth2_introspection"}],
        "authorizer": {"handler": "allow"},
        "mutators": [{"handler": "header"}]
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/part-of: naytife-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
        app.kubernetes.io/name: oathkeeper
        app.kubernetes.io/part-of: naytife-platform
    spec:
      containers:
      - name: oathkeeper
        image: oryd/oathkeeper:v0.40.9
        command:
        - oathkeeper
        - serve
        - --config
        - /etc/config/config.yaml
        ports:
        - containerPort: 8080
          name: proxy
        - containerPort: 4456
          name: api
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: rules-volume
          mountPath: /etc/rules
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 4456
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4456
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: oathkeeper-config
      - name: rules-volume
        configMap:
          name: oathkeeper-rules
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-proxy
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: proxy
  selector:
    app: oathkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-api
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 4456
    targetPort: 4456
    name: api
  selector:
    app: oathkeeper
---
# NodePort service for external access to the API Gateway
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-nodeport
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/component: proxy
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: proxy
  selector:
    app: oathkeeper
