image:
  repository: oryd/hydra-login-consent-node
  tag: v2.2.0
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: example-idp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
