apiVersion: ENC[AES256_GCM,data:cVA=,iv:U12CCrC+miFqTKonhmzmd5aV2Y7ZPKvR5xipnH0u3MQ=,tag:U/0sg3PVQo8N8JlOYmhq5g==,type:str]
kind: ENC[AES256_GCM,data:a62C+iwP,iv:gYXxEP7XtXea9cCKttjcfvCxh9LIP/lZ6AXGAFl7koY=,tag:l67L1EjvEgt6fd6BcSZxOw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MomPQKIXTD3OeaZYpvUM,iv:T18inFSa58I9wWQwVM08ax/bxzF7noIxHwd4DLFDeII=,tag:lDrWWGaHo3qk1EzkyrC/KQ==,type:str]
    namespace: ENC[AES256_GCM,data:4b08o+3yNg==,iv:MlbjC4Cmpi6CggT5ajCVLv9lXuWHizHSngV+PCbgfmk=,tag:8XPXOyXHbEXGmZdGN5Z1wQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:YcD9Ng3A0No=,iv:jLgD1uyfReuJDiTRxzEQT5G06iaC2JmzeIpEFdCD+5g=,tag:XswLYGL2FtY7wLoqOLvo2g==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:FQeCRjxKwsGSSreyTgEFzg==,iv:1bjVcB1buOaVUPRqO3UmvsMOyEsCEQUmN6uNepDNjlo=,tag:tiuw8i22GXfjWXj70AF4hw==,type:str]
type: ENC[AES256_GCM,data:k/cMlhh6,iv:fRX3KRfoa0dzN19Q9vzjIDP53y5Xz5+Qz3Vg42QXl8c=,tag:uyksNbKlswY4VRBlEbX0Ew==,type:str]
stringData:
    postgres-user: ENC[AES256_GCM,data:xTrU0nffC1g=,iv:WfFVRvmmV79zFtmexmnXp3xFDf5QbyDxftlTls+7kDA=,tag:/ciFTYpwrCJKc3gAuysrmg==,type:str]
    postgres-password: ENC[AES256_GCM,data:hse92mUvVfeyM20F3jpuFf1vSdx0,iv:wp5g10jjQJRejtbrbjv512NthkHkYXnK660urK1Pj/w=,tag:wER1GpHRVhcMR60FsshUSQ==,type:str]
    postgres-database: ENC[AES256_GCM,data:l9Rb0r/zYClX,iv:qc0ksBxITecgRv3NPL3d5FxqlcGftJa4y1Ltsn0XF3I=,tag:fWZQ20sQ4EBiaSsefCIwHg==,type:str]
sops:
    age:
        - recipient: age13ynzgj8jc2ddqj8jdq84crs6ev4yf2sa3srj00dg4y6cfk2c5p8s5rdlu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY3dweG9KTkk5RU1FaWM0
            ZnczRTFyOWpFbkFtb01ldGtYYk1yUHIrbzF3CjRiRlZJNHhUWU1iZURhTWhqbUEy
            ZG1wOW9TYjhlTkJHSExOdi9sVnhFVXMKLS0tIHY4dklUQWYybzBYTjdJNTNWaVl3
            dTJvelpKbGRKbkVCSTNETExsWXFNZzgKywITddIq1Lgyfl0c/Vkd45VHk2RdKn6x
            YuIW++C71TXMCuwQZgqlKUyJ5Xd65sDsHf+qWjni3R/xIOhMIg2SOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T00:25:12Z"
    mac: ENC[AES256_GCM,data:IfXOC26oqHSpDNyOpDM+F7BP7a3xLkAa44BxAl/Gq645mRxARDVxI3cKVorcugArWmf1kXuRGGGBTMEZo4hToI+Y8yauxD0wMSz0b563sKDczVIY5qPAWvzVRFH7B7YHza6W4dRY0+/5uZTreT06w0JWGHeigDQX7KY4lI4toWQ=,iv:zMOp1V1BcDFMg2Lwar4nqnOBA3PlZAPJm3QMMS6ffjQ=,tag:s5FEDWOnRsxCg4S+pCT8oQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
