// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shop struct {
	ID            pgtype.UUID
	Title         string
	DefaultDomain string
	FaviconUrl    pgtype.Text
	CurrencyCode  string
	About         pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}
