apiVersion: v1
kind: ConfigMap
metadata:
  name: oathkeeper-config
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/part-of: naytife-platform
data:
  config.yaml: |
    log:
      level: info
      format: json
      leak_sensitive_values: true
    
    serve:
      proxy:
        port: 8080
        host: 0.0.0.0
        cors:
          enabled: true
          allowed_origins:
            - "*"
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - "*"
      api:
        port: 4456
        host: 0.0.0.0
    
    access_rules:
      matching_strategy: glob
      repositories:
        - file:///etc/rules/access-rules.json
    
    errors:
      fallback:
        - json
      handlers:
        json:
          enabled: true
          config:
            verbose: true
        redirect:
          enabled: true
          config:
            to: ${BASE_URL}/auth/login
            when:
              - error:
                  - unauthorized
                  - forbidden
                request:
                  header:
                    accept:
                      - text/html
    
    authenticators:
      anonymous:
        enabled: true
        config:
          subject: guest
      
      noop:
        enabled: true
      
      oauth2_introspection:
        enabled: true
        config:
          introspection_url: ${HYDRA_ADMIN_URL}/admin/oauth2/introspect
          scope_strategy: exact
          trusted_issuers:
            - ${BASE_URL}/
          pre_authorization:
            enabled: true
            client_id: ${OAUTH2_CLIENT_ID}
            client_secret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - introspect
            token_url: ${HYDRA_PUBLIC_URL}/oauth2/token
          token_from:
            header: Authorization
          retry:
            max_delay: 300ms
            give_up_after: 2s
          cache:
            enabled: true
            ttl: 60s
      
      jwt:
        enabled: true
        config:
          jwks_urls:
            - ${HYDRA_PUBLIC_URL}/.well-known/jwks.json
          allowed_algorithms:
            - RS256
          trusted_issuers:
            - ${BASE_URL}/
    
    authorizers:
      allow:
        enabled: true
      
      deny:
        enabled: true
    
    mutators:
      noop:
        enabled: true
      
      header:
        enabled: true
        config:
          headers:
            X-User-Id: "{{ print .Subject }}"
            X-User-Email: "{{ print .Extra.email }}"
            X-User-Name: "{{ print .Extra.name }}"
