apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/part-of: naytife-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
        app.kubernetes.io/name: oathkeeper
        app.kubernetes.io/part-of: naytife-platform
    spec:
      containers:
      - name: oathkeeper
        image: oryd/oathkeeper:v0.40.9
        command:
        - oathkeeper
        - serve
        - --config
        - /etc/config/config.yaml
        ports:
        - containerPort: 8080
          name: proxy
        - containerPort: 4456
          name: api
        env:
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oathkeeper-secret
              key: oauth2-client-id
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oathkeeper-secret
              key: oauth2-client-secret
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: rules-volume
          mountPath: /etc/rules
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 4456
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4456
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: oathkeeper-config
      - name: rules-volume
        configMap:
          name: oathkeeper-access-rules
          items:
          - key: access-rules.json
            path: access-rules.json
