apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-proxy
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: proxy
  selector:
    app: oathkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper-api
  namespace: naytife-auth
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: naytife-platform
spec:
  type: ClusterIP
  ports:
  - port: 4456
    targetPort: 4456
    name: api
  selector:
    app: oathkeeper
