apiVersion: v1
kind: ServiceAccount
metadata:
  name: kratos-sa
  namespace: ory
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos-instance
    app.kubernetes.io/version: "v1.2.0-distroless"
