apiVersion: v1
kind: Service
metadata:
  name: kratos-public
  namespace: ory
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos-instance
    app.kubernetes.io/version: "v1.2.0-distroless"
spec:
  type: ClusterIP
  ports:
    - port: 4433
      targetPort: http-public
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos-instance
