apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: naytife
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        command:
        - sh
        - -c
        - |
          echo "Waiting for CNPG cluster to be ready..."
          until pg_isready -h naytife-postgres-pooler.naytife.svc.cluster.local -p 5432 -U naytife; do
            echo "CNPG cluster not ready, waiting 2 seconds..."
            sleep 2
          done
          echo "✅ CNPG cluster is ready!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-secret
              key: password
      
      - name: migration-pre-check
        command:
        - sh
        - -c
        - |
          echo "🔍 Running pre-migration checks..."
          
          # Check database accessibility using direct connection
          PGPASSWORD=$POSTGRES_PASSWORD psql -h naytife-postgres-pooler.naytife.svc.cluster.local -U naytife -d naytifedb -c "SELECT version();" || exit 1
          
          # Ensure schemas exist
          PGPASSWORD=$POSTGRES_PASSWORD psql -h naytife-postgres-pooler.naytife.svc.cluster.local -U naytife -d naytifedb -c "CREATE SCHEMA IF NOT EXISTS hydra;" || exit 1
          
          echo "✅ Pre-migration checks passed"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-secret
              key: password
