apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
  namespace: naytife-auth
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        command:
        - sh
        - -c
        - |
          echo "Waiting for CNPG cluster to be ready..."
          until pg_isready -h naytife-postgres-pooler.naytife.svc.cluster.local -p 5432 -U naytife; do
            echo "CNPG cluster not ready, waiting 2 seconds..."
            sleep 2
          done
          echo "✅ CNPG cluster is ready!"
