apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployer
  namespace: naytife
spec:
  template:
    spec:
      containers:
      - name: store-deployer
        imagePullPolicy: Never
        env:
        - name: APP_ENV
          value: "local"
        - name: LOG_LEVEL
          value: "debug"
