apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-registry
  namespace: naytife
spec:
  template:
    spec:
      containers:
      - name: template-registry
        imagePullPolicy: Never
        env:
        - name: APP_ENV
          value: "local"
        - name: LOG_LEVEL
          value: "debug"
