apiVersion: ENC[AES256_GCM,data:3p0=,iv:x6Ku5us400p6ozXN4lpApFJ4BGgVnhFLLQNlexe4OGA=,tag:fPkEuOeORhcvA1oln5axhg==,type:str]
kind: ENC[AES256_GCM,data:Q9ORLFxh,iv:badafBcmFzs/YpYVqIssrTg5g6bfjcjoyxJkCVImBws=,tag:ktHNq/x1RmBZrIZmCAEhiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:htsE4ApHWcMEgKJYIKaEBS6l,iv:iCvUy8VGs94qqlJOIYj2TaJDSP/U/EYb7hm0rgLriJ0=,tag:ZzRCsgpCAAtGWHx++NaqYA==,type:str]
    namespace: ENC[AES256_GCM,data:nLgw83x8Fw==,iv:A6bweD7BTcuj33A9hjVR4mJsxZrLf+a/BYmOjiej00k=,tag:/+/nfegS9D+zYRytazuH5A==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:pve9esvIRyTrPWQOOL6CVw==,iv:qvjzGcQA6vtdr2zGrPRjAtCWxZOsi/Ei9ODOt2p9eSc=,tag:fFAPJiSwQLhz3NBw9yrk6A==,type:str]
type: ENC[AES256_GCM,data:5dGoAsCo,iv:0Abl0z1tBRL7EoLBvpMtKcq+tiI/gcKrPZZ5SfJoGso=,tag:PLrqQ0VQk5OnsHdKw+Ywxg==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:nF1QbNJru7VbNO5hN5WlSccGaxvex7FmLa5JfGukAVg=,iv:CzGe7/Q9KqotKDftcX5JKofd886nGKjJ6WTrl/xnfCc=,tag:VuQPpf9f9zKSYF+lKiOE4A==,type:str]
    secret-access-key: ENC[AES256_GCM,data:q2ruc5W2o3B+pVQtlSJyPl3pRx/sByEbsp/d845KQZ6rgSxbNvSjlUtgVZMLxUjeQkQBhaLtNe6+z+gqDTyg,iv:8F8lkZNB5alqEy8LUfjl+ExF4HpQEmVaX8g2zskRv1Q=,tag:830xRfs3HMOkckib/3CqZw==,type:str]
    endpoint: ENC[AES256_GCM,data:hloy8QCfeoBRPoejcd0dX7wz4fXvuUJrPJSVPAreq+PZ/BBs9jo/7XbwIK9ave11hgj5I53iQkTf2t8=,iv:3uSqb2UicJPiYy0JFxWWZ5qiKbLWQ2CaitkLU7Bjai4=,tag:t1VKgsliCdCZXhokPSI/aw==,type:str]
    templates-bucket-name: ENC[AES256_GCM,data:pwcPz2CYjDt/,iv:22Eupa5xuGsySNW41Z9SpXu1JbDukCpO6MC1VUMQeZ4=,tag:1tXcblvP6Gs3c1bC2bw8vg==,type:str]
    stores-bucket-name: ENC[AES256_GCM,data:GaWo0tCj,iv:D01XB4d9SipUI41swbTwRsJiQzig/bRhAdPcqr+mTX8=,tag:NoBx11ANnGndL2lsl6WGJw==,type:str]
    images-bucket-name: ENC[AES256_GCM,data:vqBcVHnYK1Do0B7Amco=,iv:yuqyJgUBokma946E9wpLkNIhQUeJVcbl9l47tFEbYMk=,tag:8YPrzgveN5I1Y+LNOiRLQw==,type:str]
    templates-public-url: ENC[AES256_GCM,data:wVSCL8Qy6LbKgtEyUw964JvpmMg8W0R73BRc1LEt1rvJhcGqy1OcVzDcea49BUe91B06,iv:i4XAa8qrdZ0psnPNmvZFiQVIP2cO7GyikvwhMjivqg0=,tag:PAJHZuHm0fEdshdDFQqBrA==,type:str]
sops:
    age:
        - recipient: age1lygw3utcj5eguktcjt583e2gpcgu4m7shv2mj2cyn93z2nggpv9sua67hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5THZvUDMrd0xzYUo0NHFu
            STBqcmFSbDNZeTEySGJNSWw0am16ZW10NXhVCjVTb0hyQUtpV2hOTVRhQ0JiSk5R
            R2dPTmNvTWNNeW55c0ZnUURSRHBUbVkKLS0tIEhldTZTd0s4dk9kdE9DQ2N2dHFv
            SWdCeXdsellRVDlETzRNUUQ0b2lQeGsKbwiwkXcdbqHU7PsxiZj/2zc/WaRVUUgA
            20fc21qZhNSSfjZ4pXta0y1bOOAbqP2+vQ/b01QR7f0/A5FM15lQqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T00:25:57Z"
    mac: ENC[AES256_GCM,data:Il4Vz/T/nhAGmOHMrAQzflS8HGkMh6+P0Xo/y0QJFwIvzVjZjzUhODfAgl3oSMFWP5gSXYkCeZ/uXi0nE9G0Ui+jWGc1ZtetX1gMJABC6cplfxDZ1sTRGqlNI5CV39U6wkjlTetVGOjVWBN6BUSo+UOg2dNR68apQY1yTn6ycUo=,iv:GGL6tzIkeFxXSOOQ+HDd+e3r2aUOw4yOSSE2SGOOAng=,tag:jI6otPfqfz9o1PceezolQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
