apiVersion: ENC[AES256_GCM,data:PM8=,iv:AwMDtOESL04kfLCe6ji1+jHv9X8KHiBII6gBFIkHm3M=,tag:0DvgDJPu5d5nJY+A3WqUFg==,type:str]
kind: ENC[AES256_GCM,data:DzFCB4Ha,iv:In5ac115wEjbQxAIT4PSP2oNQ75M05CpZr886z8XHOY=,tag:af9jtUtoHufpPHtDMqorJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W1Nbp7KU2tXEcLecAX9iEP4=,iv:5R1n5s+dbpJBmcyXhd2mBnLg8T10ddug70VCTVZYo/0=,tag:HbyUIFsfDO1/Dg2Xhx8uaw==,type:str]
    namespace: ENC[AES256_GCM,data:gSmEr0LfS89k9rqJ,iv:lzbHRtpbiqpaC+r648PKYLR6VYSGtuMz+vZgD/hJV1E=,tag:226UENR+LCZoWWysgY103A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:5GIgNIz8IM9ttA==,iv:2klXIZwt/y8xqKslivu6Up8sPh22XVHvxRH6jfVW1p4=,tag:6MzWj0KQOEEwLMDC38Ikug==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:/6QmCXKLCh6FbgJEgdKs0g==,iv:YbI84IrkrdMxmhSCdhV+CP07g2PWeegf4ZzqV8rvUDI=,tag:TMBZyjfzOZ0z/n6PezFRKA==,type:str]
type: ENC[AES256_GCM,data:Jtx4ovnw,iv:R9K/M3aO0epPD3Yd4O+xGzXeBrM7nGkwdWvloN4NVgk=,tag:k9T3tuo7EvqWAer72pV0Cw==,type:str]
stringData:
    oauth2-client-id: ENC[AES256_GCM,data:/9VJrrDmJrcaEbqsXOiCtE+B7ywn/tyC7/IT,iv:tZ9irwqRDyr5p1DkJa6bCF3vIyr6EZAt87/wrITtuZM=,tag:DBCqGrRjRQW2doQ6638ypw==,type:str]
    oauth2-client-secret: ENC[AES256_GCM,data:Texqm+6AyFsFDkBkkrXuT3/2N3ys2hsadmKyjyghpA==,iv:hWlPFhz22842tnEQADt/n0qwGDTQPsprQuZoufXU4QQ=,tag:/6qoQ99H9P/+Rv+vJ0QIhg==,type:str]
sops:
    age:
        - recipient: age1lygw3utcj5eguktcjt583e2gpcgu4m7shv2mj2cyn93z2nggpv9sua67hu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTkJDazRQNUlwYmEzaW5W
            by9ibXc3aEF4YUI4MGdWTTkzakFMSFY4ZGtnCjJmd3RPSW50VGFoTzFXcWpudVFv
            M0lEUHo2djUzTmF5NHFQWWZpWUNMbFEKLS0tIFRNZjltcnJyM29EVFd3N0NZMS9H
            Z1JDeWw2bytTcXByS0haRDdLaEhtQUEKOZBRlDQXRFuQyh9HXgJVZICyhADajJY/
            MhqWwlXTyRIeISIf1ppLkdFiKwq80scERCJx5znOicKV+KMdWfPLrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T08:24:49Z"
    mac: ENC[AES256_GCM,data:cvRfMHXLK03mWYR4BEw8p2G0Krvla7J1zXtTJyOOTPxXV/nmnqPkgOQdxkfFC8EjMbPUYqAVIUtM77zSqdI4bcJuLdIfMZ2M48XnbaPH35H8tcb0ycPu7bplc+RQYgPs7rmzVmNG7nDScBc/sTx7mBRHrMEFZIDkBcbIFH/FckQ=,iv:ixnw2ZICtj57c/enR6qycPL/RoKW1tj9zSH34OWS4Kk=,tag:Nxv4mZibEMVHJWrw1zMV0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
