// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchDeleteProductAttributeValues = `-- name: BatchDeleteProductAttributeValues :batchexec
DELETE FROM product_attribute_values 
WHERE product_id = $1 
AND shop_id = $2
AND attribute_id NOT IN (SELECT UNNEST($3::int[]))
`

type BatchDeleteProductAttributeValuesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchDeleteProductAttributeValuesParams struct {
	ProductID int64   `json:"product_id"`
	ShopID    int64   `json:"shop_id"`
	Column3   []int32 `json:"column_3"`
}

func (q *Queries) BatchDeleteProductAttributeValues(ctx context.Context, arg []BatchDeleteProductAttributeValuesParams) *BatchDeleteProductAttributeValuesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProductID,
			a.ShopID,
			a.Column3,
		}
		batch.Queue(batchDeleteProductAttributeValues, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchDeleteProductAttributeValuesBatchResults{br, len(arg), false}
}

func (b *BatchDeleteProductAttributeValuesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchDeleteProductAttributeValuesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpsertProductAttributeValues = `-- name: BatchUpsertProductAttributeValues :batchexec
INSERT INTO product_attribute_values (value, attribute_option_id, product_id, attribute_id, shop_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (product_id, attribute_id, shop_id) 
DO UPDATE SET 
    value = EXCLUDED.value,
    attribute_option_id = EXCLUDED.attribute_option_id
WHERE product_attribute_values.value IS DISTINCT FROM EXCLUDED.value  
   OR product_attribute_values.attribute_option_id IS DISTINCT FROM EXCLUDED.attribute_option_id
RETURNING product_attribute_value_id, value, attribute_option_id, product_id, attribute_id, shop_id
`

type BatchUpsertProductAttributeValuesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertProductAttributeValuesParams struct {
	Value             *string `json:"value"`
	AttributeOptionID *int64  `json:"attribute_option_id"`
	ProductID         int64   `json:"product_id"`
	AttributeID       int64   `json:"attribute_id"`
	ShopID            int64   `json:"shop_id"`
}

func (q *Queries) BatchUpsertProductAttributeValues(ctx context.Context, arg []BatchUpsertProductAttributeValuesParams) *BatchUpsertProductAttributeValuesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Value,
			a.AttributeOptionID,
			a.ProductID,
			a.AttributeID,
			a.ShopID,
		}
		batch.Queue(batchUpsertProductAttributeValues, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertProductAttributeValuesBatchResults{br, len(arg), false}
}

func (b *BatchUpsertProductAttributeValuesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertProductAttributeValuesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteProductVariants = `-- name: DeleteProductVariants :batchexec
DELETE FROM product_variations
WHERE shop_id = $1 AND product_id = $2
AND product_variation_id != ALL($3::bigint[])
`

type DeleteProductVariantsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteProductVariantsParams struct {
	ShopID              int64   `json:"shop_id"`
	ProductID           int64   `json:"product_id"`
	ProductVariationIds []int64 `json:"product_variation_ids"`
}

func (q *Queries) DeleteProductVariants(ctx context.Context, arg []DeleteProductVariantsParams) *DeleteProductVariantsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ShopID,
			a.ProductID,
			a.ProductVariationIds,
		}
		batch.Queue(deleteProductVariants, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteProductVariantsBatchResults{br, len(arg), false}
}

func (b *DeleteProductVariantsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteProductVariantsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertProductVariants = `-- name: UpsertProductVariants :batchexec
INSERT INTO product_variations (slug, description, price,sku, available_quantity, seo_description, seo_keywords, seo_title, product_id, shop_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (slug, shop_id)
DO UPDATE SET
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    sku = EXCLUDED.sku,
    available_quantity = EXCLUDED.available_quantity,
    seo_description = EXCLUDED.seo_description,
    seo_keywords = EXCLUDED.seo_keywords,
    seo_title = EXCLUDED.seo_title
RETURNING product_variation_id, sku, slug, description, price, available_quantity, seo_description, seo_keywords, seo_title, created_at, updated_at, product_id, shop_id
`

type UpsertProductVariantsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertProductVariantsParams struct {
	Slug              string         `json:"slug"`
	Description       string         `json:"description"`
	Price             pgtype.Numeric `json:"price"`
	Sku               string         `json:"sku"`
	AvailableQuantity int64          `json:"available_quantity"`
	SeoDescription    *string        `json:"seo_description"`
	SeoKeywords       []string       `json:"seo_keywords"`
	SeoTitle          *string        `json:"seo_title"`
	ProductID         int64          `json:"product_id"`
	ShopID            int64          `json:"shop_id"`
}

func (q *Queries) UpsertProductVariants(ctx context.Context, arg []UpsertProductVariantsParams) *UpsertProductVariantsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Slug,
			a.Description,
			a.Price,
			a.Sku,
			a.AvailableQuantity,
			a.SeoDescription,
			a.SeoKeywords,
			a.SeoTitle,
			a.ProductID,
			a.ShopID,
		}
		batch.Queue(upsertProductVariants, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertProductVariantsBatchResults{br, len(arg), false}
}

func (b *UpsertProductVariantsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertProductVariantsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
