// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attribute struct {
	AttributeID int64   `json:"attribute_id"`
	Title       string  `json:"title"`
	InputType   string  `json:"input_type"`
	Unit        *string `json:"unit"`
	Required    bool    `json:"required"`
	ShopID      int64   `json:"shop_id"`
}

type AttributeValue struct {
	AttributeValueID int64  `json:"attribute_value_id"`
	Title            string `json:"title"`
	Value            string `json:"value"`
	BooleanValue     *bool  `json:"boolean_value"`
	ShopID           int64  `json:"shop_id"`
	AttributeID      int64  `json:"attribute_id"`
}

type Category struct {
	CategoryID  int64   `json:"category_id"`
	Slug        string  `json:"slug"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	ParentID    *int64  `json:"parent_id"`
	ShopID      int64   `json:"shop_id"`
}

type Order struct {
	OrderID    int64              `json:"order_id"`
	Status     string             `json:"status"`
	TotalPrice pgtype.Numeric     `json:"total_price"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     uuid.UUID          `json:"user_id"`
}

type OrderItem struct {
	OrderItemID        int64              `json:"order_item_id"`
	Quantity           int64              `json:"quantity"`
	Price              pgtype.Numeric     `json:"price"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProductVariationID int64              `json:"product_variation_id"`
	OrderID            int64              `json:"order_id"`
}

type Product struct {
	ProductID     int64              `json:"product_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryID    int64              `json:"category_id"`
	ShopID        int64              `json:"shop_id"`
	ProductTypeID int64              `json:"product_type_id"`
}

type ProductImage struct {
	ProductImageID int64  `json:"product_image_id"`
	Url            string `json:"url"`
	Alt            string `json:"alt"`
	ProductID      int64  `json:"product_id"`
	ShopID         int64  `json:"shop_id"`
}

type ProductType struct {
	ProductTypeID int64  `json:"product_type_id"`
	Title         string `json:"title"`
	Shippable     bool   `json:"shippable"`
	Digital       bool   `json:"digital"`
	ShopID        int64  `json:"shop_id"`
}

type ProductVariation struct {
	ProductVariationID int64              `json:"product_variation_id"`
	Slug               string             `json:"slug"`
	Description        string             `json:"description"`
	Price              pgtype.Numeric     `json:"price"`
	AvailableQuantity  int64              `json:"available_quantity"`
	SeoDescription     *string            `json:"seo_description"`
	SeoKeywords        []string           `json:"seo_keywords"`
	SeoTitle           *string            `json:"seo_title"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProductID          int64              `json:"product_id"`
	ShopID             int64              `json:"shop_id"`
	Sku                string             `json:"sku"`
	Status             string             `json:"status"`
}

type Shop struct {
	ShopID              int64              `json:"shop_id"`
	OwnerID             uuid.UUID          `json:"owner_id"`
	Title               string             `json:"title"`
	Domain              string             `json:"domain"`
	Email               string             `json:"email"`
	CurrencyCode        string             `json:"currency_code"`
	Status              string             `json:"status"`
	About               *string            `json:"about"`
	Address             *string            `json:"address"`
	PhoneNumber         *string            `json:"phone_number"`
	SeoDescription      *string            `json:"seo_description"`
	SeoKeywords         []string           `json:"seo_keywords"`
	SeoTitle            *string            `json:"seo_title"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	WhatsappPhoneNumber *string            `json:"whatsapp_phone_number"`
	WhatsappLink        *string            `json:"whatsapp_link"`
	FacebookLink        *string            `json:"facebook_link"`
	InstagramLink       *string            `json:"instagram_link"`
}

type ShopImage struct {
	ShopImageID   int64   `json:"shop_image_id"`
	FaviconUrl    *string `json:"favicon_url"`
	LogoUrl       *string `json:"logo_url"`
	BannerUrl     *string `json:"banner_url"`
	CoverImageUrl *string `json:"cover_image_url"`
	ShopID        int64   `json:"shop_id"`
}

type ShoppingCart struct {
	ShoppingCartID int64     `json:"shopping_cart_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type ShoppingCartItem struct {
	ShoppingCartItemID int64              `json:"shopping_cart_item_id"`
	Quantity           int64              `json:"quantity"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProductVariationID int64              `json:"product_variation_id"`
	ShoppingCartID     int64              `json:"shopping_cart_id"`
}

type User struct {
	UserID         uuid.UUID        `json:"user_id"`
	Provider       *string          `json:"provider"`
	Email          *string          `json:"email"`
	Name           *string          `json:"name"`
	ProfilePicture *string          `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastLogin      pgtype.Timestamp `json:"last_login"`
	ProviderID     *string          `json:"provider_id"`
	Locale         *string          `json:"locale"`
}
