// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shop.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShop = `-- name: CreateShop :one
INSERT INTO shops (owner_id, title, domain,email, currency_code, about, status, address,phone_number, seo_description, seo_keywords, seo_title)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING shop_id, owner_id, title, domain, email, currency_code, status, about, address, phone_number, seo_description, seo_keywords, seo_title, updated_at, created_at
`

type CreateShopParams struct {
	OwnerID        uuid.UUID
	Title          string
	Domain         string
	Email          string
	CurrencyCode   string
	About          pgtype.Text
	Status         string
	Address        pgtype.Text
	PhoneNumber    pgtype.Text
	SeoDescription pgtype.Text
	SeoKeywords    []string
	SeoTitle       pgtype.Text
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.OwnerID,
		arg.Title,
		arg.Domain,
		arg.Email,
		arg.CurrencyCode,
		arg.About,
		arg.Status,
		arg.Address,
		arg.PhoneNumber,
		arg.SeoDescription,
		arg.SeoKeywords,
		arg.SeoTitle,
	)
	var i Shop
	err := row.Scan(
		&i.ShopID,
		&i.OwnerID,
		&i.Title,
		&i.Domain,
		&i.Email,
		&i.CurrencyCode,
		&i.Status,
		&i.About,
		&i.Address,
		&i.PhoneNumber,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.SeoTitle,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShop = `-- name: GetShop :one
SELECT shop_id, owner_id, title, domain, email, currency_code, status, about, address, phone_number, seo_description, seo_keywords, seo_title, updated_at, created_at FROM shops
WHERE shop_id = $1
`

func (q *Queries) GetShop(ctx context.Context, shopID int64) (Shop, error) {
	row := q.db.QueryRow(ctx, getShop, shopID)
	var i Shop
	err := row.Scan(
		&i.ShopID,
		&i.OwnerID,
		&i.Title,
		&i.Domain,
		&i.Email,
		&i.CurrencyCode,
		&i.Status,
		&i.About,
		&i.Address,
		&i.PhoneNumber,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.SeoTitle,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShopByDomain = `-- name: GetShopByDomain :one
SELECT shop_id, owner_id, title, domain, email, currency_code, status, about, address, phone_number, seo_description, seo_keywords, seo_title, updated_at, created_at FROM shops
WHERE domain = $1
`

func (q *Queries) GetShopByDomain(ctx context.Context, domain string) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByDomain, domain)
	var i Shop
	err := row.Scan(
		&i.ShopID,
		&i.OwnerID,
		&i.Title,
		&i.Domain,
		&i.Email,
		&i.CurrencyCode,
		&i.Status,
		&i.About,
		&i.Address,
		&i.PhoneNumber,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.SeoTitle,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getShopFacebook = `-- name: GetShopFacebook :one
SELECT facebook_id, handle, url, shop_id FROM facebooks
WHERE shop_id = $1
`

func (q *Queries) GetShopFacebook(ctx context.Context, shopID int64) (Facebook, error) {
	row := q.db.QueryRow(ctx, getShopFacebook, shopID)
	var i Facebook
	err := row.Scan(
		&i.FacebookID,
		&i.Handle,
		&i.Url,
		&i.ShopID,
	)
	return i, err
}

const getShopIDByDomain = `-- name: GetShopIDByDomain :one
SELECT shop_id FROM shops
WHERE domain = $1
`

func (q *Queries) GetShopIDByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRow(ctx, getShopIDByDomain, domain)
	var shop_id int64
	err := row.Scan(&shop_id)
	return shop_id, err
}

const getShopImages = `-- name: GetShopImages :one
SELECT shop_image_id, favicon_url, logo_url, banner_url, cover_image_url, shop_id FROM shop_images
WHERE shop_id = $1
`

func (q *Queries) GetShopImages(ctx context.Context, shopID int64) (ShopImage, error) {
	row := q.db.QueryRow(ctx, getShopImages, shopID)
	var i ShopImage
	err := row.Scan(
		&i.ShopImageID,
		&i.FaviconUrl,
		&i.LogoUrl,
		&i.BannerUrl,
		&i.CoverImageUrl,
		&i.ShopID,
	)
	return i, err
}

const getShopWhatsApp = `-- name: GetShopWhatsApp :one
SELECT whatsapp_id, phone_number, url, shop_id FROM whatsapps
WHERE shop_id = $1
`

func (q *Queries) GetShopWhatsApp(ctx context.Context, shopID int64) (Whatsapp, error) {
	row := q.db.QueryRow(ctx, getShopWhatsApp, shopID)
	var i Whatsapp
	err := row.Scan(
		&i.WhatsappID,
		&i.PhoneNumber,
		&i.Url,
		&i.ShopID,
	)
	return i, err
}

const getShopsByOwner = `-- name: GetShopsByOwner :many
SELECT shop_id, owner_id, title, domain, email, currency_code, status, about, address, phone_number, seo_description, seo_keywords, seo_title, updated_at, created_at FROM shops
WHERE owner_id = $1
`

func (q *Queries) GetShopsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Shop, error) {
	rows, err := q.db.Query(ctx, getShopsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ShopID,
			&i.OwnerID,
			&i.Title,
			&i.Domain,
			&i.Email,
			&i.CurrencyCode,
			&i.Status,
			&i.About,
			&i.Address,
			&i.PhoneNumber,
			&i.SeoDescription,
			&i.SeoKeywords,
			&i.SeoTitle,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET 
    title = COALESCE($1, title),
    currency_code = COALESCE($2, currency_code),
    about = COALESCE($3, about),
    status = COALESCE($4, status),
    phone_number = COALESCE($5, phone_number),
    seo_description = COALESCE($6, seo_description),
    seo_keywords = COALESCE($7, seo_keywords),
    seo_title = COALESCE($8, seo_title),
    address = COALESCE($9, address),
    email = COALESCE($10, email)
WHERE shop_id = $11
RETURNING shop_id, owner_id, title, domain, email, currency_code, status, about, address, phone_number, seo_description, seo_keywords, seo_title, updated_at, created_at
`

type UpdateShopParams struct {
	Title          pgtype.Text
	CurrencyCode   pgtype.Text
	About          pgtype.Text
	Status         pgtype.Text
	PhoneNumber    pgtype.Text
	SeoDescription pgtype.Text
	SeoKeywords    []string
	SeoTitle       pgtype.Text
	Address        pgtype.Text
	Email          pgtype.Text
	ShopID         int64
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShop,
		arg.Title,
		arg.CurrencyCode,
		arg.About,
		arg.Status,
		arg.PhoneNumber,
		arg.SeoDescription,
		arg.SeoKeywords,
		arg.SeoTitle,
		arg.Address,
		arg.Email,
		arg.ShopID,
	)
	var i Shop
	err := row.Scan(
		&i.ShopID,
		&i.OwnerID,
		&i.Title,
		&i.Domain,
		&i.Email,
		&i.CurrencyCode,
		&i.Status,
		&i.About,
		&i.Address,
		&i.PhoneNumber,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.SeoTitle,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertShopFacebook = `-- name: UpsertShopFacebook :one
INSERT INTO facebooks (shop_id, url, handle)
VALUES ($1, $2, $3)
ON CONFLICT (shop_id)
DO UPDATE SET url = EXCLUDED.url, handle = EXCLUDED.handle
RETURNING facebook_id, handle, url, shop_id
`

type UpsertShopFacebookParams struct {
	ShopID int64
	Url    string
	Handle string
}

func (q *Queries) UpsertShopFacebook(ctx context.Context, arg UpsertShopFacebookParams) (Facebook, error) {
	row := q.db.QueryRow(ctx, upsertShopFacebook, arg.ShopID, arg.Url, arg.Handle)
	var i Facebook
	err := row.Scan(
		&i.FacebookID,
		&i.Handle,
		&i.Url,
		&i.ShopID,
	)
	return i, err
}

const upsertShopWhatsapp = `-- name: UpsertShopWhatsapp :one
INSERT INTO whatsapps (shop_id, url, phone_number)
VALUES ($1, $2, $3)
ON CONFLICT (shop_id)
DO UPDATE SET url = EXCLUDED.url, phone_number = EXCLUDED.phone_number
RETURNING whatsapp_id, phone_number, url, shop_id
`

type UpsertShopWhatsappParams struct {
	ShopID      int64
	Url         string
	PhoneNumber string
}

func (q *Queries) UpsertShopWhatsapp(ctx context.Context, arg UpsertShopWhatsappParams) (Whatsapp, error) {
	row := q.db.QueryRow(ctx, upsertShopWhatsapp, arg.ShopID, arg.Url, arg.PhoneNumber)
	var i Whatsapp
	err := row.Scan(
		&i.WhatsappID,
		&i.PhoneNumber,
		&i.Url,
		&i.ShopID,
	)
	return i, err
}
