apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: naytife
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: naytife-platform
data:
  01-init.sql: |
    -- Create schema for Hydra if it doesn't exist
    CREATE SCHEMA IF NOT EXISTS hydra;
    
    -- Create additional schemas as needed
    CREATE SCHEMA IF NOT EXISTS naytife_schema;
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON SCHEMA hydra TO postgres;
    GRANT ALL PRIVILEGES ON SCHEMA naytife_schema TO postgres;
