name: Build and Railway Deploy

on:
  push:
    branches:
      - stage # Or your main branch

jobs:
  build:
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.6" # Adjust to your Go version

      # Not sure why i need this
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Change directory to backend
        run: cd backend

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy
        working-directory: ./backend

      # Install Atlas CLI
      - name: Install Atlas CLI
        run: |
          curl -sSf https://atlasgo.sh | sh

      # Build the Go application
      - name: Build
        run: make build
        working-directory: ./backend

      # Migrate the database (optional step if required)
      - name: Apply Migrations with Atlas
        run: atlas migrate apply --env prod --url ${{ secrets.DATABASE_URL }}
        working-directory: ./backend

      - name: Install Railway
        run: npm i -g @railway/cli
